---
abstract: 'Geocode addresses with the TomTom Map Toolkit API'
author:
  - 'gray <gray@cpan.org>'
build_requires:
  Test::More: '0.82'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Geo-Coder-TomTom
no_index:
  directory:
    - t
    - inc
recommends:
  JSON::XS: '2'
  LWP::Protocol::https: '6.02'
requires:
  Encode: '0'
  JSON: '2'
  LWP::UserAgent: '0'
  URI: '1.36'
resources:
  repository: http://github.com/gray/geo-coder-tomtom
version: '0.04'
