--- #YAML:1.0
name:               Geo-Coder-TomTom
version:            0.03
abstract:           Geocode addresses with the TomTom route planner
author:
    - gray <gray@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Encode:      0
    Test::More:  0.82
requires:
    JSON:            2
    LWP::UserAgent:  0
    URI:             1.36
    URI::Escape:     0
resources:
    repository:  http://github.com/gray/geo-coder-tomtom
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    JSON::XS:  2
